// ==========================================
// PDF Report Generator
// ==========================================
// Generates professional PDF reports for expense data.
// Uses pdfkit for server-side PDF generation.
// Supports monthly summaries and detailed expense lists.

import PDFDocument from "pdfkit";

interface ExpenseRow {
  date: string;
  description: string;
  category: string;
  cloudProvider: string;
  amount: number;
}

interface ReportData {
  title: string;
  period: string;
  totalAmount: number;
  expenses: ExpenseRow[];
  generatedAt: string;
}

/**
 * Generates a PDF buffer for expense reports.
 * Returns a readable stream that can be piped to response.
 */
export const generateExpenseReportPDF = (
  data: ReportData
): Promise<Buffer> => {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50, size: "A4" });
    const chunks: Buffer[] = [];

    doc.on("data", (chunk: Buffer) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    // Title
    doc
      .fontSize(24)
      .font("Helvetica-Bold")
      .text(data.title, { align: "center" });

    // Subtitle
    doc
      .fontSize(12)
      .font("Helvetica")
      .text(`Period: ${data.period}`, { align: "center" })
      .text(`Generated: ${data.generatedAt}`, { align: "center" })
      .moveDown();

    // Total
    doc
      .fontSize(16)
      .font("Helvetica-Bold")
      .text(`Total: $${data.totalAmount.toFixed(2)}`, { align: "center" })
      .moveDown();

    // Table header
    const tableTop = doc.y;
    const colWidths = [80, 150, 80, 100, 80];
    const headers = ["Date", "Description", "Category", "Provider", "Amount"];

    doc.fontSize(10).font("Helvetica-Bold");
    headers.forEach((header, i) => {
      const x = 50 + colWidths.slice(0, i).reduce((a, b) => a + b, 0);
      doc.text(header, x, tableTop, { width: colWidths[i], align: "left" });
    });

    // Draw header line
    doc
      .moveTo(50, tableTop + 18)
      .lineTo(545, tableTop + 18)
      .stroke();

    // Table rows
    doc.font("Helvetica").fontSize(9);
    let y = tableTop + 25;

    data.expenses.forEach((expense, index) => {
      if (y > 750) {
        doc.addPage();
        y = 50;
      }

      // Alternate row background for readability
      if (index % 2 === 0) {
        doc.rect(50, y - 3, 495, 18).fill("#f5f5f5");
        doc.fill("black");
      }

      const values = [
        expense.date,
        expense.description.substring(0, 30),
        expense.category,
        expense.cloudProvider,
        `$${expense.amount.toFixed(2)}`,
      ];

      values.forEach((val, i) => {
        const x = 50 + colWidths.slice(0, i).reduce((a, b) => a + b, 0);
        doc.text(val, x, y, { width: colWidths[i], align: "left" });
      });

      y += 18;
    });

    // Footer
    doc
      .fontSize(8)
      .font("Helvetica")
      .fillColor("gray")
      .text(
        "Generated by Cloud Expense Tracker",
        50,
        doc.page.height - 50,
        { align: "center" }
      );

    doc.end();
  });
};
